In [1]:
from lxml import etree
import numpy as np
import pandas as pd

In [2]:
def extract_duration(s):
    c=0
    duration=''
    for i in list(s):
        if(i==':'):
            c+=1
        if(c==2):
            duration+=i
        if(c==3):
            break
    return duration[1:]

In [4]:
import subprocess
host='ACCESS-DENIED\SQLEXPRESS'

q5_time=[]
for i in range(50):
    durations=[]
    path="G:\dbquery-optimizer\query-variants\query_5\q_five_"+str(i+1)+".sql"
    for j in range(10):
        p=subprocess.Popen(['sqlcmd','-S',host,'-i',path,'-p1'],stdout=subprocess.PIPE)
        stdout=p.communicate()[0]
        # print(stdout)
        f_index=str(stdout).find('affected')
        l_index=f_index+25
        s=str(stdout[f_index+3:l_index])
        d=int(extract_duration(s))
        durations.append(d)
    q5_time.append(durations)

q5_time=np.array(q5_time)
q5_time=pd.DataFrame(q5_time)
q5_time

       0    1    2    3    4    5    6    7    8    9
0   1266  156  156  156  156  157  172  156  156  140
1    812  140  125  109  110  125  125  109  125  141
2    266   63   47   47   47   46   47   47   62   47
3     63   63   63   62   63   47   63   62   62   47
4     62   31   46   62   47   62   62   47   47   47
5     78   47   47   47   46   46   63   47   47   47
6     62   62   31   47   47   46   47   47   47   32
7     78   47   47   47   63   46   47   47   63   47
8    141  141  141  141  140  156  156  156  141  141
9     62   62   47   47   47   32   47   32   31   31
10   734  187  125  125  125  109  125  125  125  125
11    62   47   46   47   47   47   47   47   31   47
12    63   47   31   31   31   47   47   47   46   47
13    78   78   62   63   47   62   78   63   63   62
14    62   62   47   62   63   62   47   63   63   63
15    47   31   47   47   47   47   47   31   46   47
16    63   47   47   63   47   47   47   47   63   47
17    62   47   62   47   47   63   47   47   47   46
18    63   46   47   47   47   47   47   47   47   47
19    78   46   47   47   47   63   47   47   46   63
20    62   47   47   62   47   46   47   47   47   47
21    78   62   62   63   63   62   63   63   78   63
22    31   47   31   47   47   47   47   47   47   47
23   593  188  140  125  125  125  125  125  125  125
24    62   47   47   46   63   62   47   47   46   62
25    63   47   47   47   47   47   47   47   47   47
26    62   47   47   47   32   31   46   47   47   47
27    62   47   46   63   47   47   47   47   47   47
28    78   31   46   47   47   47   47   47   47   47
29    63   47   47   47   47   47   47   47   63   47
30    94   63   62   63   47   46   47   47   47   47
31    78   47   47   46   47   47   47   47   63   47
32    63   47   47   47   47   32   47   47   47   46
33    47   47   32   47   47   47   47   47   47   47
34    47   46   47   47   47   47   47   47   46   47
35    78   63   62   47   47   63   63   62   47   47
36    63   47   46   47   47   63   63   62   63   62
37    46   31   31   47   47   47   47   47   47   31
38    78   47   47   31   31   46   31   47   47   47
39    78   46   47   47   62   62   62   47   47   47
40    62   46   47   63   62   63   63   62   63   62
41    62   31   31   47   31   31   46   47   31   47
42    63   47   46   47   47   47   47   47   46   47
43    62   47   63   47   63   63   47   62   47   63
44    93   47   47   62   63   47   46   47   63   47
45    47   63   47   47   63   47   47   63   47   47
46   875  719  484  656  282  125  125  125  125  125
47    78   93   62   46   47   47   47   47   47   47
48    78   63   78   47   63   47   47   47   47   63
49    79   47   63   47   47   63   63   47   62   47

In [18]:
q5_time['mean']=q5_time.iloc[:,1:].mean(axis=1)
q_list=[]
for i in range(50):
    if(q5_time['mean'][i]>=50.0):
        q_list.append(i)

q5_time

       0    1    2    3    4    5    6    7    8    9        mean
0   1266  156  156  156  156  157  172  156  156  140  156.111111
1    812  140  125  109  110  125  125  109  125  141  123.222222
2    266   63   47   47   47   46   47   47   62   47   50.333333
3     63   63   63   62   63   47   63   62   62   47   59.111111
4     62   31   46   62   47   62   62   47   47   47   50.111111
5     78   47   47   47   46   46   63   47   47   47   48.555556
6     62   62   31   47   47   46   47   47   47   32   45.111111
7     78   47   47   47   63   46   47   47   63   47   50.444444
8    141  141  141  141  140  156  156  156  141  141  145.888889
9     62   62   47   47   47   32   47   32   31   31   41.777778
10   734  187  125  125  125  109  125  125  125  125  130.111111
11    62   47   46   47   47   47   47   47   31   47   45.111111
12    63   47   31   31   31   47   47   47   46   47   41.555556
13    78   78   62   63   47   62   78   63   63   62   64.222222
14    62   62   47   62   63   62   47   63   63   63   59.111111
15    47   31   47   47   47   47   47   31   46   47   43.333333
16    63   47   47   63   47   47   47   47   63   47   50.555556
17    62   47   62   47   47   63   47   47   47   46   50.333333
18    63   46   47   47   47   47   47   47   47   47   46.888889
19    78   46   47   47   47   63   47   47   46   63   50.333333
20    62   47   47   62   47   46   47   47   47   47   48.555556
21    78   62   62   63   63   62   63   63   78   63   64.333333
22    31   47   31   47   47   47   47   47   47   47   45.222222
23   593  188  140  125  125  125  125  125  125  125  133.666667
24    62   47   47   46   63   62   47   47   46   62   51.888889
25    63   47   47   47   47   47   47   47   47   47   47.000000
26    62   47   47   47   32   31   46   47   47   47   43.444444
27    62   47   46   63   47   47   47   47   47   47   48.666667
28    78   31   46   47   47   47   47   47   47   47   45.111111
29    63   47   47   47   47   47   47   47   63   47   48.777778
30    94   63   62   63   47   46   47   47   47   47   52.111111
31    78   47   47   46   47   47   47   47   63   47   48.666667
32    63   47   47   47   47   32   47   47   47   46   45.222222
33    47   47   32   47   47   47   47   47   47   47   45.333333
34    47   46   47   47   47   47   47   47   46   47   46.777778
35    78   63   62   47   47   63   63   62   47   47   55.666667
36    63   47   46   47   47   63   63   62   63   62   55.555556
37    46   31   31   47   47   47   47   47   47   31   41.666667
38    78   47   47   31   31   46   31   47   47   47   41.555556
39    78   46   47   47   62   62   62   47   47   47   51.888889
40    62   46   47   63   62   63   63   62   63   62   59.000000
41    62   31   31   47   31   31   46   47   31   47   38.000000
42    63   47   46   47   47   47   47   47   46   47   46.777778
43    62   47   63   47   63   63   47   62   47   63   55.777778
44    93   47   47   62   63   47   46   47   63   47   52.111111
45    47   63   47   47   63   47   47   63   47   47   52.333333
46   875  719  484  656  282  125  125  125  125  125  307.333333
47    78   93   62   46   47   47   47   47   47   47   53.666667
48    78   63   78   47   63   47   47   47   47   63   55.777778
49    79   47   63   47   47   63   63   47   62   47   54.000000

In [3]:
q_list=[0, 1, 2, 3, 4, 7, 8, 10, 13, 14, 16, 17, 19, 21, 23, 24, 30, 35, 36, 39, 40, 43, 44, 45, 46, 47, 48, 49]

In [4]:
import re

def make_template(file,params,replacedParams):
    tree=etree.parse(file)
    xmlstr=etree.tostring(tree)
    xmlstr=xmlstr.decode("utf-8")
    for i in range(len(params)):
        xmlstr,count=re.subn(params[i],replacedParams[i],xmlstr)
        print("{} occurences replaced".format(count))
    xmlstr=xmlstr.replace("'","''")
    return xmlstr


def use_template(file,params,replacedParams):
    tree=etree.parse(file)
    xmlstr=etree.tostring(tree)
    xmlstr=xmlstr.decode("utf-8")
    for i in range(len(params)):
        xmlstr,count=re.subn(params[i],replacedParams[i],xmlstr)
        # print("{} occurences replaced".format(count))
    return xmlstr

def extract_parameters(query):
    params=[]
    s=query
    s_index=query.find("cn.country_code ='")+len("cn.country_code ='")
    param1=''
    while(s[s_index]!="'"):
        param1+=s[s_index]
        s_index+=1
    params.append(param1)
    s_index=query.find("k.keyword ='")+len("k.keyword ='")
    param2=''
    while(s[s_index]!="'"):
        param2+=s[s_index]
        s_index+=1
    params.append(param2)
    return params

In [10]:
f=open("G:\dbquery-optimizer\query-variants\query_5\q_five_49.sql",'r')
q=f.read()
print(extract_parameters(q))

['[om]', 'home-alone']

In [11]:
file=r"G:\dbquery-optimizer\Execution Plans\query_5\query_five_49.xml"
params=["\[om\]","home-alone"]
print(params)
replacedParams=['C_CODE','K_TYPE']
s=make_template(file,params,replacedParams)
f=open(r'G:\dbquery-optimizer\Execution Plans\operator-based\plan_five_3.xml','w')
f.write(s)
f.close()

['\\[om\\]', 'home-alone']
3 occurences replaced
3 occurences replaced

In [12]:
p_list=[1,2,3]
for i in range(len(q_list)):
    f=open("G:\dbquery-optimizer\query-variants\query_5\q_five_"+str(q_list[i]+1)+".sql",'r')
    q=f.read()
    f.close()
    params=['C_CODE','K_TYPE']
    replacedParams=extract_parameters(q)
    for j in range(len(p_list)):
        file=r"G:\dbquery-optimizer\Execution Plans\operator-based\plan_five_"+str(p_list[j])+".xml"
        plan=use_template(file,params,replacedParams)
        q1=q.replace(';','')+"OPTION( MAXDOP 1, USE PLAN N'"+plan+"')"
        f=open(r"G:\dbquery-optimizer\new_query_5\query_"+str(q_list[i]+1)+"_plan_"+str(p_list[j])+".sql",'w')
        f.write(q1)
        f.close()

In [13]:
for i in range(len(q_list)):
    f=open(r"G:\dbquery-optimizer\query-variants\query_5\q_five_"+str(q_list[i]+1)+".sql",'r')
    q=f.read()
    f.close()
    f=open(r"G:\dbquery-optimizer\new_query_5\query_"+str(q_list[i]+1)+"_no_plan.sql",'w')
    q1=q.replace(';','')+"OPTION( MAXDOP 1)"
    f.write(q1)
    f.close()
    f=open("G:\dbquery-optimizer\Execution Plans\query_5\query_five_"+str(q_list[i]+1)+".xml",'r',encoding='utf-16')
    plan=f.read()
    f.close()
    plan=plan.replace("'","''")
    q1=q.replace(';','')+"OPTION( MAXDOP 1,USE PLAN N'"+plan+"')"
    f=open(r"G:\dbquery-optimizer\new_query_5\query_"+str(q_list[i]+1)+"_default_plan.sql",'w')
    f.write(q1)
    f.close()

In [14]:
import subprocess
import os
host='ACCESS-DENIED\SQLEXPRESS'
folder=r"G:\dbquery-optimizer\new_query_5"
directory = os.fsencode(folder)
q5p_time=[]  
for file in os.listdir(directory):
    path=os.path.join(directory,file)
    path=path.decode("utf-8")
    durations=[]
    for j in range(5):
        p=subprocess.Popen(['sqlcmd','-S',host,'-i',path,'-p1'],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        stdout, stderr=p.communicate()
        try:
            f_index=str(stdout).find('affected')
            l_index=f_index+25
            s=str(stdout[f_index+3:l_index])
            d=int(extract_duration(s))
            durations.append(d)
        except:
            print(stderr)
    q5p_time.append(durations)

q5p_time=np.array(q5p_time)
q5p_time=pd.DataFrame(q5p_time)
q5p_time

         0       1     2     3       4
0     3016     156   125   109     125
1      750     171   125   125     125
2      391     187   141   125     125
3       79      63    63    63      63
4       63      47    62    47      47
..     ...     ...   ...   ...     ...
135    890     266   156   140     156
136    453     171   172   188     172
137    563    1016   968  4266    3406
138   3250    1859  2781  5562    3016
139  91375  127813   610  1781  126328

[140 rows x 5 columns]

In [19]:
q5p_time=pd.DataFrame(q5p_time)
# pd.set_option('display.max_rows',10)
q5p_time['mean']=q5p_time.iloc[:,1:].mean(axis=1)
q5p_time

         0       1     2     3       4      mean
0     3016     156   125   109     125    128.75
1      750     171   125   125     125    136.50
2      391     187   141   125     125    144.50
3       79      63    63    63      63     63.00
4       63      47    62    47      47     50.75
..     ...     ...   ...   ...     ...       ...
135    890     266   156   140     156    179.50
136    453     171   172   188     172    175.75
137    563    1016   968  4266    3406   2414.00
138   3250    1859  2781  5562    3016   3304.50
139  91375  127813   610  1781  126328  64133.00

[140 rows x 6 columns]

In [26]:
q5p_stats=[]
i=0
k=0
while(i<139):
    durations=[]
    durations.append(q_list[k]+1)
    k+=1
    for j in range(5):
        durations.append(q5p_time['mean'][i])
        i+=1
    q5p_stats.append(durations)

q5p_stats=np.array(q5p_stats)

q5p_stats=pd.DataFrame({'Query_No':q5p_stats[:,0],'No Plan':q5p_stats[:,2],'Default Plan':q5p_stats[:,1],'Plan 1':q5p_stats[:,3],'Plan 2':q5p_stats[:,4],'Plan 3':q5p_stats[:,5]})
q5p_stats['mean_duration']=q5p_stats.iloc[:,1:6].mean(axis=1)
q5p_stats['min_duration']=q5p_stats.iloc[:,1:6].min(axis=1)
q5p_stats['max_duration']=q5p_stats.iloc[:,1:6].max(axis=1)
q5p_stats['std deviation']=q5p_stats.iloc[:,1:6].std(axis=1)
q5p_stats.style.set_caption("(All durations in ms)")
q5p_stats=q5p_stats.astype({'Query_No':int})
q5p_stats=q5p_stats.drop([27])
sum=pd.DataFrame({'Query_No':['Sum'],'No Plan':[q5p_stats['No Plan'].sum()],'Default Plan':[q5p_stats['Default Plan'].sum()],'Plan 1':[q5p_stats['Plan 1'].sum()],'Plan 2':[q5p_stats['Plan 2'].sum()],'Plan 3':[q5p_stats['Plan 3'].sum()]})
# q5p_stats['Query_No']='Sum'
# q5p_stats.to_csv()

q5p_stats=q5p_stats.append(sum,ignore_index=False,sort=False)
q5p_stats.to_excel('Query_5_Plan_stats(operator-based).xls')

q5p_stats

,Query_No,No Plan,Default Plan,Plan 1,Plan 2,Plan 3,mean_duration,min_duration,max_duration,std deviation
0,1,136.50,128.75,144.50,63.00,50.75,104.70,50.75,144.50,44.224357
1,2,58.50,58.50,62.75,50.50,50.75,56.20,50.50,62.75,5.377616
2,3,54.50,42.75,137.00,62.25,46.75,68.65,42.75,137.00,38.933678
3,4,50.75,51.00,50.75,51.00,46.75,50.05,46.75,51.00,1.848986
4,5,54.50,51.00,58.75,51.00,47.00,52.45,47.00,58.75,4.410215
5,8,179.25,156.25,191.50,332.00,203.25,212.45,156.25,332.00,69.058716
6,9,54.50,62.25,62.00,50.50,50.50,55.95,50.50,62.25,5.869412
7,11,66.00,82.50,62.25,51.00,62.75,64.90,51.00,82.50,11.355891
8,14,140.75,155.75,168.25,70.75,62.00,119.50,62.00,168.25,49.560569
9,15,46.75,62.75,58.50,82.00,70.50,64.10,46.75,82.00,13.186878
10,17,148.25,195.25,152.25,70.25,90.00,131.20,70.25,195.25,50.617561
11,18,66.25,62.25,74.50,55.00,47.00,61.00,47.00,74.50,10.528236
12,20,58.50,58.75,128.75,58.50,54.75,71.85,54.75,128.75,31.851511
13,22,58.75,58.25,66.50,46.75,54.75,57.00,46.75,66.50,7.158911
14,24,62.50,59.00,73.75,58.25,63.00,63.30,58.25,73.75,6.203326
15,25,66.50,62.00,59.00,54.75,62.00,60.85,54.75,66.50,4.335897
16,31,70.25,78.50,74.75,62.50,63.00,69.80,62.50,78.50,7.069742
17,36,62.50,62.50,148.25,62.50,58.75,78.90,58.75,148.25,38.801820
18,37,62.00,58.75,78.25,70.25,82.00,70.25,58.75,82.00,10.029644
19,40,66.25,82.00,58.00,54.25,62.00,64.50,54.25,82.00,10.757265
20,41,234.50,160.25,136.75,71.00,67.00,133.90,67.00,234.50,69.380878
21,44,59.00,59.00,77.75,58.50,54.25,61.70,54.25,77.75,9.191368
22,45,62.50,73.75,70.25,59.00,59.00,64.90,59.00,73.75,6.751389
23,46,66.50,47.00,74.50,58.75,47.00,58.75,47.00,74.50,12.085632
24,47,63.00,82.00,62.75,58.50,55.00,64.25,55.00,82.00,10.458250
25,48,54.25,50.75,54.50,50.75,66.50,55.35,50.75,66.50,6.491822
26,49,74.00,74.50,74.25,78.25,67.00,73.60,67.00,78.25,4.079675
0,Sum,2177.50,2176.00,2461.00,1891.75,1744.00,NaN,NaN,NaN,NaN