In [3]:
from lxml import etree
import numpy as np
import pandas as pd

In [4]:
def extract_duration(s):
    c=0
    duration=''
    for i in list(s):
        if(i==':'):
            c+=1
        if(c==2):
            duration+=i
        if(c==3):
            break
    return duration[1:]

In [23]:
import subprocess
host='ACCESS-DENIED\SQLEXPRESS'

q2_time=[]
for i in range(50):
    durations=[]
    path="G:\dbquery-optimizer\query-variants\query_2\q_two_"+str(i+1)+".sql"
    for j in range(10):
        p=subprocess.Popen(['sqlcmd','-S',host,'-i',path,'-p1'],stdout=subprocess.PIPE)
        stdout=p.communicate()[0]
        # print(stdout)
        f_index=str(stdout).find('affected')
        l_index=f_index+25
        s=str(stdout[f_index+3:l_index])
        d=int(extract_duration(s))
        durations.append(d)
    q2_time.append(durations)

q2_time=np.array(q2_time)
q2_time=pd.DataFrame(q2_time)
q2_time

      0    1    2    3    4    5    6    7    8    9
0   110   63   63   46   62   63   62   63   63   62
1   454   94   94   78   78   78   94   78   78   94
2    78   63   47   62   62   62   62   63   47   47
3    78   47   47   47   47   46   47   47   62   63
4   110   78   78   78   78   78   78   94   79   94
5   547  547  141  125  125  125  125  125  125  125
6    78   62   78   63   63   78   62   62   62   62
7   109   78   78   78   63   79   78   62   78   78
8   500  563  140  141  140  141  140  141  141  125
9    78   47   62   63   47   63   62   62   47   47
10   94   62   78   78   78   78   78   62   78   78
11   78   62   62   63   47   62   63   46   62   63
12   94   78   78   78   78   78   79   79   78   78
13  109   78   78   94   93   78   93   94   94   93
14   94   78   62   78   78   78   78   94   78   63
15   94   47   63   63   46   47   47   62   62   47
16  110   78   78   78   78   62   63   63   62   62
17  109   78   94   78   78   78   93   78   78   79
18   78   63   47   47   63   63   62   47   47   62
19   78   47   62   62   63   63   47   62   63   63
20   78   63   47   63   63   47   47   47   62   63
21  109   78   93   94  109   94   78   78   93   94
22   94   78   79   78   63   78   79   78   78   78
23  125   93   94   94   78   78   94   94  109   94
24   94   78   78   78   78   78   62   63   63   79
25  125   94   93   94   94   78   94   93   94   94
26   94   62   62   62   78   63   63   63   78   78
27  110   78   78   78   78   94   78   78   78   78
28   94   94   78   78   78   62   78   78   78   63
29   94   79   94   78   93   78   78   93   94  110
30   78   62   78   62   62   63   63   63   63   79
31   94   63   63   62   78   78   62   78   63   63
32  610  907  375  141  125  141  125  125  125  141
33   78   63   62   46   62   62   63   63   63   63
34   93   94   78   78   78   78   78   78   93   78
35   94   62   78   63   62   78   62   63   78   79
36  125   93   78   94   93   94   94   94   93   94
37   93   94   78   78   78   93   78   78   94   78
38   94   63   78   78   63   63   62   78   63   63
39  109   79   94   78   93   94   94   78   78   94
40  109   78   93   94   94   94   93  109   94   94
41  110   78   78   78   78   62   78   78   78   78
42   79   63   63   63   63   63   78   62   62   62
43  125   94   94   78   94   93   94  109   93   94
44   94   63   47   62   78   62   62   62   62   62
45   93   62   62   78   63   63   63   62   62   62
46  109   78   94   78   78   78   94   79   78   78
47   93   62   63   63   63   63   62   62   62   62
48  125   79   94   78   94   94   93   78   93   94
49  703  406  359  109  110  109  109  110  110  125

In [26]:
q2_time['mean']=q2_time.iloc[:,1:].mean(axis=1)
q_list=[]
for i in range(50):
    if(q2_time['mean'][i]>=75.0):
        q_list.append(i)

q2_time

      0    1    2    3    4    5    6    7    8    9        mean
0   110   63   63   46   62   63   62   63   63   62   60.777778
1   454   94   94   78   78   78   94   78   78   94   85.111111
2    78   63   47   62   62   62   62   63   47   47   57.222222
3    78   47   47   47   47   46   47   47   62   63   50.333333
4   110   78   78   78   78   78   78   94   79   94   81.666667
5   547  547  141  125  125  125  125  125  125  125  173.666667
6    78   62   78   63   63   78   62   62   62   62   65.777778
7   109   78   78   78   63   79   78   62   78   78   74.666667
8   500  563  140  141  140  141  140  141  141  125  185.777778
9    78   47   62   63   47   63   62   62   47   47   55.555556
10   94   62   78   78   78   78   78   62   78   78   74.444444
11   78   62   62   63   47   62   63   46   62   63   58.888889
12   94   78   78   78   78   78   79   79   78   78   78.222222
13  109   78   78   94   93   78   93   94   94   93   88.333333
14   94   78   62   78   78   78   78   94   78   63   76.333333
15   94   47   63   63   46   47   47   62   62   47   53.777778
16  110   78   78   78   78   62   63   63   62   62   69.333333
17  109   78   94   78   78   78   93   78   78   79   81.555556
18   78   63   47   47   63   63   62   47   47   62   55.666667
19   78   47   62   62   63   63   47   62   63   63   59.111111
20   78   63   47   63   63   47   47   47   62   63   55.777778
21  109   78   93   94  109   94   78   78   93   94   90.111111
22   94   78   79   78   63   78   79   78   78   78   76.555556
23  125   93   94   94   78   78   94   94  109   94   92.000000
24   94   78   78   78   78   78   62   63   63   79   73.000000
25  125   94   93   94   94   78   94   93   94   94   92.000000
26   94   62   62   62   78   63   63   63   78   78   67.666667
27  110   78   78   78   78   94   78   78   78   78   79.777778
28   94   94   78   78   78   62   78   78   78   63   76.333333
29   94   79   94   78   93   78   78   93   94  110   88.555556
30   78   62   78   62   62   63   63   63   63   79   66.111111
31   94   63   63   62   78   78   62   78   63   63   67.777778
32  610  907  375  141  125  141  125  125  125  141  245.000000
33   78   63   62   46   62   62   63   63   63   63   60.777778
34   93   94   78   78   78   78   78   78   93   78   81.444444
35   94   62   78   63   62   78   62   63   78   79   69.444444
36  125   93   78   94   93   94   94   94   93   94   91.888889
37   93   94   78   78   78   93   78   78   94   78   83.222222
38   94   63   78   78   63   63   62   78   63   63   67.888889
39  109   79   94   78   93   94   94   78   78   94   86.888889
40  109   78   93   94   94   94   93  109   94   94   93.666667
41  110   78   78   78   78   62   78   78   78   78   76.222222
42   79   63   63   63   63   63   78   62   62   62   64.333333
43  125   94   94   78   94   93   94  109   93   94   93.666667
44   94   63   47   62   78   62   62   62   62   62   62.222222
45   93   62   62   78   63   63   63   62   62   62   64.111111
46  109   78   94   78   78   78   94   79   78   78   81.666667
47   93   62   63   63   63   63   62   62   62   62   62.444444
48  125   79   94   78   94   94   93   78   93   94   88.555556
49  703  406  359  109  110  109  109  110  110  125  171.888889

In [35]:
q_list=[1, 4, 5, 8, 12, 13, 14, 17, 21, 22, 23, 25, 27, 28, 29, 32, 34, 36, 37, 39, 40, 41, 43, 46, 48, 49]

In [29]:
import re

def make_template(file,params,replacedParams):
    tree=etree.parse(file)
    xmlstr=etree.tostring(tree)
    xmlstr=xmlstr.decode("utf-8")
    for i in range(len(params)):
        xmlstr,count=re.subn(params[i],replacedParams[i],xmlstr)
        print("{} occurences replaced".format(count))
    xmlstr=xmlstr.replace("'","''")
    return xmlstr


def use_template(file,params,replacedParams):
    tree=etree.parse(file)
    xmlstr=etree.tostring(tree)
    xmlstr=xmlstr.decode("utf-8")
    for i in range(len(params)):
        xmlstr,count=re.subn(params[i],replacedParams[i],xmlstr)
        # print("{} occurences replaced".format(count))
    return xmlstr

def extract_parameters(query):
    params=[]
    s=query
    s_index=query.find("it.info ='")+len("it.info ='")
    param1=''
    while(s[s_index]!="'"):
        param1+=s[s_index]
        s_index+=1
    params.append(param1)
    s_index=query.find("mi_idx.info > '")+len("mi_idx.info > '")
    param2=''
    while(s[s_index]!="'"):
        param2+=s[s_index]
        s_index+=1
    params.append(param2)
    s_index=query.find('t.production_year > ')+len('t.production_year > ')
    param3=''
    while(s[s_index]!='\n'):
        param3+=s[s_index]
        s_index+=1
    params.append(param3)
    return params

In [34]:
f=open("G:\dbquery-optimizer\query-variants\query_2\q_two_49.sql",'r')
q=f.read()
print(extract_parameters(q))

['books', '465.6', '2002']

In [41]:
file=r"G:\dbquery-optimizer\Execution Plans\query_2\query_two_40.xml"
params=["novel","450.3","2012"]
print(params)
replacedParams=['INFO_TYPE','INFO','P_YEAR']
s=make_template(file,params,replacedParams)
f=open(r'G:\dbquery-optimizer\Execution Plans\operator-based\plan_two_5.xml','w')
f.write(s)
f.close()

['novel', '450.3', '2012']
3 occurences replaced
3 occurences replaced
3 occurences replaced

In [42]:
p_list=[1,2,3,4,5]
for i in range(len(q_list)):
    f=open("G:\dbquery-optimizer\query-variants\query_2\q_two_"+str(q_list[i]+1)+".sql",'r')
    q=f.read()
    f.close()
    params=['INFO_TYPE','INFO','P_YEAR']
    replacedParams=extract_parameters(q)
    for j in range(len(p_list)):
        file=r"G:\dbquery-optimizer\Execution Plans\operator-based\plan_two_"+str(p_list[j])+".xml"
        plan=use_template(file,params,replacedParams)
        q1=q.replace(';','')+"OPTION( MAXDOP 1, USE PLAN N'"+plan+"')"
        f=open(r"G:\dbquery-optimizer\new_query_2\query_"+str(q_list[i]+1)+"_plan_"+str(p_list[j])+".sql",'w')
        f.write(q1)
        f.close()

In [43]:
for i in range(len(q_list)):
    f=open(r"G:\dbquery-optimizer\query-variants\query_2\q_two_"+str(q_list[i]+1)+".sql",'r')
    q=f.read()
    f.close()
    f=open(r"G:\dbquery-optimizer\new_query_2\query_"+str(q_list[i]+1)+"_no_plan.sql",'w')
    q1=q.replace(';','')+"OPTION( MAXDOP 1)"
    f.write(q1)
    f.close()
    f=open("G:\dbquery-optimizer\Execution Plans\query_2\query_two_"+str(q_list[i]+1)+".xml",'r',encoding='utf-16')
    plan=f.read()
    f.close()
    plan=plan.replace("'","''")
    q1=q.replace(';','')+"OPTION( MAXDOP 1,USE PLAN N'"+plan+"')"
    f=open(r"G:\dbquery-optimizer\new_query_2\query_"+str(q_list[i]+1)+"_default_plan.sql",'w')
    f.write(q1)
    f.close()

In [44]:
import subprocess
import os
host='ACCESS-DENIED\SQLEXPRESS'
folder=r"G:\dbquery-optimizer\new_query_2"
directory = os.fsencode(folder)
q2p_time=[]  
for file in os.listdir(directory):
    path=os.path.join(directory,file)
    path=path.decode("utf-8")
    durations=[]
    for j in range(5):
        p=subprocess.Popen(['sqlcmd','-S',host,'-i',path,'-p1'],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        stdout, stderr=p.communicate()
        try:
            f_index=str(stdout).find('affected')
            l_index=f_index+25
            s=str(stdout[f_index+3:l_index])
            d=int(extract_duration(s))
            durations.append(d)
        except:
            print(stderr)
    q2p_time.append(durations)

q2p_time=np.array(q2p_time)
q2p_time=pd.DataFrame(q2p_time)
q2p_time

        0     1     2     3     4
0    1782   187   328   375   343
1     375   297   265   188   203
2     265   281   203   235   188
3     218   156   172   172   219
4     187   172   156   187   203
..    ...   ...   ...   ...   ...
177   343   282   282   297   313
178  1297  1266  1390  1594  1094
179   296   344   313   375   281
180  1359  1265  1282  1421  1093
181   297   328   250   375   297

[182 rows x 5 columns]

In [45]:
q2p_time=pd.DataFrame(q2p_time)
# pd.set_option('display.max_rows',10)
q2p_time['mean']=q2p_time.iloc[:,1:].mean(axis=1)
q2p_time

        0     1     2     3     4     mean
0    1782   187   328   375   343   308.25
1     375   297   265   188   203   238.25
2     265   281   203   235   188   226.75
3     218   156   172   172   219   179.75
4     187   172   156   187   203   179.50
..    ...   ...   ...   ...   ...      ...
177   343   282   282   297   313   293.50
178  1297  1266  1390  1594  1094  1336.00
179   296   344   313   375   281   328.25
180  1359  1265  1282  1421  1093  1265.25
181   297   328   250   375   297   312.50

[182 rows x 6 columns]

In [47]:
q2p_stats=[]
i=0
k=0
while(i<182):
    durations=[]
    durations.append(q_list[k]+1)
    k+=1
    for j in range(7):
        durations.append(q2p_time['mean'][i])
        i+=1
    q2p_stats.append(durations)

q2p_stats=np.array(q2p_stats)

q2p_stats=pd.DataFrame({'Query_No':q2p_stats[:,0],'No Plan':q2p_stats[:,2],'Default Plan':q2p_stats[:,1],'Plan 1':q2p_stats[:,3],'Plan 2':q2p_stats[:,4],'Plan 3':q2p_stats[:,5],'Plan 4':q2p_stats[:,6],'Plan 5':q2p_stats[:,7]})
q2p_stats['mean_duration']=q2p_stats.iloc[:,1:8].mean(axis=1)
q2p_stats['min_duration']=q2p_stats.iloc[:,1:8].min(axis=1)
q2p_stats['max_duration']=q2p_stats.iloc[:,1:8].max(axis=1)
q2p_stats['std deviation']=q2p_stats.iloc[:,1:8].std(axis=1)
q2p_stats.style.set_caption("(All durations in ms)")
q2p_stats=q2p_stats.astype({'Query_No':int})
sum=pd.DataFrame({'Query_No':['Sum'],'No Plan':[q2p_stats['No Plan'].sum()],'Default Plan':[q2p_stats['Default Plan'].sum()],'Plan 1':[q2p_stats['Plan 1'].sum()],'Plan 2':[q2p_stats['Plan 2'].sum()],'Plan 3':[q2p_stats['Plan 3'].sum()],'Plan 4':[q2p_stats['Plan 4'].sum()],'Plan 5':[q2p_stats['Plan 5'].sum()]})
# q2p_stats['Query_No']='Sum'
# q2p_stats.to_csv()

q2p_stats=q2p_stats.append(sum,ignore_index=False,sort=False)
q2p_stats.to_excel('Query_2_Plan_stats(operator-based).xls')